/*
Package cli implements a minimal viable CLI library.

All flags are optional. All arguments are required.

Flags and argument functions follow the same patterns and support
the same types as the standard library `flag`, with additions.
The `Value` and `Getter` interfaces from `flag` is reused.

Defining root flags and arguments:

	var root Root = cli.Root()

	root.Help = "Tell me about your self!"

	age      := root.IntFlag("age", "Your age.", -1)
	name     := root.StringArg(0, "name", "Your name")
	parents  := root.StringArgs(1, 2, "parents", "Your parents names")
	siblings := root.StringRest("siblings", "Your siblings names")
	verbose  := root.BoolFlag("verbose", "Be verbose about it")

	root.Run(func() {
		if *verbose {
			fmt.Println("I'm verbose!")
		}
		fmt.Printf("Hello %v (%v)", *name, *age)
		fmt.Printf("Family: %v - %v", parents, siblings)
	})

	root.Parse([]string{"verbose", "age=4", "Stewie", "Peter", "Louis", "Meg", "Chris"})

Defining commands:

	var cmd0 Command = root.Command("prices", "List prices")

	sorting := cmd0.EnumFlag("sort", "Sort by (default: price)", "price", "product")
	desc    := cmd0.BoolFlag("descending", "Sort descending instead of ascending")

	cmd0.Run(func() {
		switch *sorting {
		case "price":
			// Print sorted by price...
		case "product":
			// Print sorted by product...
		}
	})

	root.Parse([]string{"prices", "sort=product"})

	cmd1  := root.Command("prices:add", "Add a new price")
	price := cmd1.Float64Arg("price", "Unit price")
	prod  := cmd1.StringArg("product", "Related product")

The `help` command is autogenerated, and returns:

	Tell me about your self!

	Options:
	  age=<int>             Your age.
	  verbose               Be verbose about it
	  <string:name>         Your name
	  <string:parents{2}>   Your parents names
	  <string:siblings...>  Your siblings names

	Commands:
	  prices                List prices
	    sort=price|product  Sort by (default: price)
	    descending          Sort descending instead of ascending

	  prices:add          Add a new price
	    <float:price>     Unit price
		<string:product>  Related product

Calling `help prices` will return:

	prices                List prices
	  sort=price|product  Sort by (default: price)
	  descending          Sort descending instead of ascending
*/
package cli

import "flag"

type Flag struct {
	Name     string     // name as it appears on command line
	Usage    string     // help message
	Value    flag.Value // value as set
	DefValue string     // default value (as text); for usage message
}

type Argument struct {
	Name     string     // name as it appears on command line
	Usage    string     // help message
	Value    flag.Value // value as set
	Position []int      // one integer is abs position, two integers is a range, empty is rest
}

type RunFunc func() error

type Command struct {
	flags     map[string]*Flag
	arguments map[string]*Argument
	run       RunFunc
}

type Root struct {
	Command
	commands map[string]*Command
	Help     string
}

// @Todo Flags to support:
//
// BoolFlag(name string, usage string) *bool // Default is always false
// BoolFuncFlag(name, usage string, fn func(string) error)
// BoolVarFlag(p *bool, name string, usage string, value bool)
// DurationFlag(name string, usage string, value time.Duration) *time.Duration
// DurationVarFlag(p *time.Duration, name string, usage string, value time.Duration)
// Float64Flag(name string, usage string, value float64) *float64
// Float64VarFlag(p *float64, name string, usage string, value float64)
// FuncFlag(name, usage string, fn func(string) error)
// IntFlag(name string, usage string, value int) *int
// Int64Flag(name string, usage string, value int64) *int64
// Int64VarFlag(p *int64, name string, usage string, value int64)
// IntVarFlag(p *int, name string, usage string, value int)
// StringFlag(name string, usage string, value string) *string
// StringVarFlag(p *string, name string, usage string, value string)
// TextVarFlag(p encoding.TextUnmarshaler, name string, usage string, value encoding.TextMarshaler)
// UintFlag(name string, usage string, value uint) *uint
// Uint64Flag(name string, usage string, value uint64) *uint64
// Uint64VarFlag(p *uint64, name string, usage string, value uint64)
// UintVarFlag(p *uint, name string, usage string, value uint)
// VarFlag(value Value, name string, usage string)
//
// EnumFlag(name string, usage string, values ...string) *string // First value is also default

// Arguments support all the same types, but with these patterns:
//
// *Arg(i, name, usage) // Argument at index
// *Args(i0, i1, name, usage) // List of arguments at range [i0,i1]
// *Rest(name, usage) // Remainder of arguments
